export const COUNTRIES: CustomSelectOption[] = [
  { value: 'afghanistan', name: 'Afghanistan' },
  { value: 'aland_islands', name: 'Aland Islands' },
  { value: 'albania', name: 'Albania' },
  { value: 'algeria', name: 'Algeria' },
  { value: 'american_samoa', name: 'American Samoa' },
  { value: 'andorra', name: 'Andorra' },
  { value: 'angola', name: 'Angola' },
  { value: 'anguilla', name: 'Anguilla' },
  { value: 'antarctica', name: 'Antarctica' },
  { value: 'antigua_and_barbuda', name: 'Antigua and Barbuda' },
  { value: 'argentina', name: 'Argentina' },
  { value: 'armenia', name: 'Armenia' },
  { value: 'aruba', name: 'Aruba' },
  { value: 'australia', name: 'Australia' },
  { value: 'austria', name: 'Austria' },
  { value: 'azerbaijan', name: 'Azerbaijan' },
  { value: 'bahamas', name: 'Bahamas' },
  { value: 'bahrain', name: 'Bahrain' },
  { value: 'bangladesh', name: 'Bangladesh' },
  { value: 'barbados', name: 'Barbados' },
  { value: 'belarus', name: 'Belarus' },
  { value: 'belgium', name: 'Belgium' },
  { value: 'belize', name: 'Belize' },
  { value: 'benin', name: 'Benin' },
  { value: 'bermuda', name: 'Bermuda' },
  { value: 'bhutan', name: 'Bhutan' },
  { value: 'bolivia', name: 'Bolivia' },
  { value: 'bonaire', name: 'Bonaire' },
  { value: 'bosnia_and_herzegovina', name: 'Bosnia and Herzegovina' },
  { value: 'botswana', name: 'Botswana' },
  { value: 'bouvet_island', name: 'Bouvet Island' },
  { value: 'brazil', name: 'Brazil' },
  { value: 'brunei_darussalam', name: 'Brunei Darussalam' },
  { value: 'bulgaria', name: 'Bulgaria' },
  { value: 'burkina_faso', name: 'Burkina Faso' },
  { value: 'burundi', name: 'Burundi' },
  { value: 'cabo_verde', name: 'Cabo Verde' },
  { value: 'cambodia', name: 'Cambodia' },
  { value: 'cameroon', name: 'Cameroon' },
  { value: 'canada', name: 'Canada' },
  { value: 'cayman_islands', name: 'Cayman Islands' },
  { value: 'central_african_republic', name: 'Central African Republic' },
  { value: 'chad', name: 'Chad' },
  { value: 'chile', name: 'Chile' },
  { value: 'china', name: 'China' },
  { value: 'christmas_island', name: 'Christmas Island' },
  { value: 'cocos_islands', name: 'Cocos Islands' },
  { value: 'colombia', name: 'Colombia' },
  { value: 'comoros', name: 'Comoros' },
  { value: 'congo', name: 'Congo' },
  { value: 'congo', name: 'Congo' },
  { value: 'cook_islands', name: 'Cook Islands' },
  { value: 'costa_rica', name: 'Costa Rica' },
  { value: "cote_d'ivoire", name: "Cote d'Ivoire" },
  { value: 'croatia', name: 'Croatia' },
  { value: 'cuba', name: 'Cuba' },
  { value: 'curacao', name: 'Curacao' },
  { value: 'cyprus', name: 'Cyprus' },
  { value: 'czech_republic', name: 'Czech Republic' },
  { value: 'denmark', name: 'Denmark' },
  { value: 'djibouti', name: 'Djibouti' },
  { value: 'dominica', name: 'Dominica' },
  { value: 'dominican_republic', name: 'Dominican Republic' },
  { value: 'ecuador', name: 'Ecuador' },
  { value: 'egypt', name: 'Egypt' },
  { value: 'el_salvador', name: 'El Salvador' },
  { value: 'equatorial_guinea', name: 'Equatorial Guinea' },
  { value: 'eritrea', name: 'Eritrea' },
  { value: 'estonia', name: 'Estonia' },
  { value: 'ethiopia', name: 'Ethiopia' },
  { value: 'falkland_islands', name: 'Falkland Islands' },
  { value: 'faroe_islands', name: 'Faroe Islands' },
  { value: 'fiji', name: 'Fiji' },
  { value: 'finland', name: 'Finland' },
  { value: 'france', name: 'France' },
  { value: 'french_guiana', name: 'French Guiana' },
  { value: 'french_polynesia', name: 'French Polynesia' },
  { value: 'french_southern_territories', name: 'French Southern Territories' },
  { value: 'gabon', name: 'Gabon' },
  { value: 'gambia', name: 'Gambia' },
  { value: 'georgia', name: 'Georgia' },
  { value: 'germany', name: 'Germany' },
  { value: 'ghana', name: 'Ghana' },
  { value: 'gibraltar', name: 'Gibraltar' },
  { value: 'greece', name: 'Greece' },
  { value: 'greenland', name: 'Greenland' },
  { value: 'grenada', name: 'Grenada' },
  { value: 'guadeloupe', name: 'Guadeloupe' },
  { value: 'guam', name: 'Guam' },
  { value: 'guatemala', name: 'Guatemala' },
  { value: 'guernsey', name: 'Guernsey' },
  { value: 'guinea', name: 'Guinea' },
  { value: 'guinea-bissau', name: 'Guinea-Bissau' },
  { value: 'guyana', name: 'Guyana' },
  { value: 'haiti', name: 'Haiti' },
  { value: 'heard_and_mcdonald_islands', name: 'Heard and McDonald Islands' },
  { value: 'holy_see', name: 'Holy See' },
  { value: 'honduras', name: 'Honduras' },
  { value: 'hong_kong', name: 'Hong Kong' },
  { value: 'hungary', name: 'Hungary' },
  { value: 'iceland', name: 'Iceland' },
  { value: 'india', name: 'India' },
  { value: 'indonesia', name: 'Indonesia' },
  { value: 'iran', name: 'Iran' },
  { value: 'iraq', name: 'Iraq' },
  { value: 'ireland', name: 'Ireland' },
  { value: 'isle_of_man', name: 'Isle of Man' },
  { value: 'israel', name: 'Israel' },
  { value: 'italy', name: 'Italy' },
  { value: 'jamaica', name: 'Jamaica' },
  { value: 'japan', name: 'Japan' },
  { value: 'jersey', name: 'Jersey' },
  { value: 'jordan', name: 'Jordan' },
  { value: 'kazakhstan', name: 'Kazakhstan' },
  { value: 'kenya', name: 'Kenya' },
  { value: 'kiribati', name: 'Kiribati' },
  { value: 'korea', name: 'Korea' },
  { value: 'korea', name: 'Korea' },
  { value: 'kuwait', name: 'Kuwait' },
  { value: 'kyrgyzstan', name: 'Kyrgyzstan' },
  { value: 'lao_peoples', name: "Lao People's" },
  { value: 'latvia', name: 'Latvia' },
  { value: 'lebanon', name: 'Lebanon' },
  { value: 'lesotho', name: 'Lesotho' },
  { value: 'liberia', name: 'Liberia' },
  { value: 'libya', name: 'Libya' },
  { value: 'liechtenstein', name: 'Liechtenstein' },
  { value: 'lithuania', name: 'Lithuania' },
  { value: 'luxembourg', name: 'Luxembourg' },
  { value: 'macao', name: 'Macao' },
  { value: 'macedonia', name: 'Macedonia' },
  { value: 'madagascar', name: 'Madagascar' },
  { value: 'malawi', name: 'Malawi' },
  { value: 'malaysia', name: 'Malaysia' },
  { value: 'maldives', name: 'Maldives' },
  { value: 'mali', name: 'Mali' },
  { value: 'malta', name: 'Malta' },
  { value: 'marshall_islands', name: 'Marshall Islands' },
  { value: 'martinique', name: 'Martinique' },
  { value: 'mauritania', name: 'Mauritania' },
  { value: 'mauritius', name: 'Mauritius' },
  { value: 'mayotte', name: 'Mayotte' },
  { value: 'mexico', name: 'Mexico' },
  { value: 'micronesia', name: 'Micronesia' },
  { value: 'moldova', name: 'Moldova' },
  { value: 'monaco', name: 'Monaco' },
  { value: 'mongolia', name: 'Mongolia' },
  { value: 'montenegro', name: 'Montenegro' },
  { value: 'montserrat', name: 'Montserrat' },
  { value: 'morocco', name: 'Morocco' },
  { value: 'mozambique', name: 'Mozambique' },
  { value: 'myanmar', name: 'Myanmar' },
  { value: 'namibia', name: 'Namibia' },
  { value: 'nauru', name: 'Nauru' },
  { value: 'nepal', name: 'Nepal' },
  { value: 'netherlands', name: 'Netherlands' },
  { value: 'new_caledonia', name: 'New Caledonia' },
  { value: 'new_zealand', name: 'New Zealand' },
  { value: 'nicaragua', name: 'Nicaragua' },
  { value: 'niger', name: 'Niger' },
  { value: 'nigeria', name: 'Nigeria' },
  { value: 'niue', name: 'Niue' },
  { value: 'norfolk_island', name: 'Norfolk Island' },
  { value: 'northern_mariana_islands', name: 'Northern Mariana Islands' },
  { value: 'norway', name: 'Norway' },
  { value: 'oman', name: 'Oman' },
  { value: 'pakistan', name: 'Pakistan' },
  { value: 'palau', name: 'Palau' },
  { value: 'palestine', name: 'Palestine' },
  { value: 'panama', name: 'Panama' },
  { value: 'papua_new_guinea', name: 'Papua New Guinea' },
  { value: 'paraguay', name: 'Paraguay' },
  { value: 'peru', name: 'Peru' },
  { value: 'philippines', name: 'Philippines' },
  { value: 'pitcairn', name: 'Pitcairn' },
  { value: 'poland', name: 'Poland' },
  { value: 'portugal', name: 'Portugal' },
  { value: 'puerto_rico', name: 'Puerto Rico' },
  { value: 'qatar', name: 'Qatar' },
  { value: 'reunion', name: 'Reunion' },
  { value: 'romania', name: 'Romania' },
  { value: 'russian_federation', name: 'Russian Federation' },
  { value: 'rwanda', name: 'Rwanda' },
  { value: 'saint_barthelemy', name: 'Saint Barthelemy' },
  { value: 'saint_helena', name: 'Saint Helena' },
  { value: 'saint_kitts_and_nevis', name: 'Saint Kitts and Nevis' },
  { value: 'saint_lucia', name: 'Saint Lucia' },
  { value: 'saint_martin', name: 'Saint Martin' },
  { value: 'saint_pierre_and_miquelon', name: 'Saint Pierre and Miquelon' },
  {
    value: 'saint_vincent_and_the_grenadines',
    name: 'Saint Vincent and the Grenadines',
  },
  { value: 'samoa', name: 'Samoa' },
  { value: 'san_marino', name: 'San Marino' },
  { value: 'sao_tome_and_principe', name: 'Sao Tome and Principe' },
  { value: 'saudi_arabia', name: 'Saudi Arabia' },
  { value: 'senegal', name: 'Senegal' },
  { value: 'serbia', name: 'Serbia' },
  { value: 'seychelles', name: 'Seychelles' },
  { value: 'sierra_leone', name: 'Sierra Leone' },
  { value: 'singapore', name: 'Singapore' },
  { value: 'sint_maarten', name: 'Sint Maarten' },
  { value: 'slovakia', name: 'Slovakia' },
  { value: 'slovenia', name: 'Slovenia' },
  { value: 'solomon_islands', name: 'Solomon Islands' },
  { value: 'somalia', name: 'Somalia' },
  { value: 'south_africa', name: 'South Africa' },
  { value: 'south_georgia', name: 'South Georgia' },
  { value: 'south_sudan', name: 'South Sudan' },
  { value: 'spain', name: 'Spain' },
  { value: 'sri_lanka', name: 'Sri Lanka' },
  { value: 'sudan', name: 'Sudan' },
  { value: 'suriname', name: 'Suriname' },
  { value: 'svalbard_and_jan mayen', name: 'Svalbard and Jan Mayen' },
  { value: 'swaziland', name: 'Swaziland' },
  { value: 'sweden', name: 'Sweden' },
  { value: 'switzerland', name: 'Switzerland' },
  { value: 'syrian_arab_republic', name: 'Syrian Arab Republic' },
  { value: 'taiwan', name: 'Taiwan' },
  { value: 'tajikistan', name: 'Tajikistan' },
  { value: 'tanzania', name: 'Tanzania' },
  { value: 'thailand', name: 'Thailand' },
  { value: 'timor_leste', name: 'Timor Leste' },
  { value: 'togo', name: 'Togo' },
  { value: 'tokelau', name: 'Tokelau' },
  { value: 'tonga', name: 'Tonga' },
  { value: 'trinidad_and_tobago', name: 'Trinidad and Tobago' },
  { value: 'tunisia', name: 'Tunisia' },
  { value: 'turkey', name: 'Turkey' },
  { value: 'turkmenistan', name: 'Turkmenistan' },
  { value: 'turks_and_caicos islands', name: 'Turks and Caicos Islands' },
  { value: 'tuvalu', name: 'Tuvalu' },
  { value: 'uganda', name: 'Uganda' },
  { value: 'ukraine', name: 'Ukraine' },
  { value: 'united_arab_emirates', name: 'United Arab Emirates' },
  { value: 'united_kingdom', name: 'United Kingdom' },
  { value: 'united_states_of america', name: 'United States of America' },
  { value: 'uruguay', name: 'Uruguay' },
  { value: 'uzbekistan', name: 'Uzbekistan' },
  { value: 'vanuatu', name: 'Vanuatu' },
  { value: 'venezuela', name: 'Venezuela' },
  { value: 'viet_nam', name: 'Viet Nam' },
  { value: 'virgin_islands', name: 'Virgin Islands' },
  { value: 'virgin_islands', name: 'Virgin Islands' },
  { value: 'wallis_and_futuna', name: 'Wallis and Futuna' },
  { value: 'western_sahara', name: 'Western Sahara' },
  { value: 'yemen', name: 'Yemen' },
  { value: 'zambia', name: 'Zambia' },
  { value: 'zimbabwe', name: 'Zimbabwe' },
];
